### ISSUE TITLE
Webpack example should show loading and using JSAPI modules

### ISSUE THREAD

**Issue by tomwayson** [jpeterson/devsummit-2016-modern-tools#2]
Webpack example [doesn't load any modules from the JSAPI](https://github.com/jpeterson/devsummit-2016-modern-tools/tree/master/example-webpack-amd). Not sure how useful it is if it doesn't show that's possible. I've tried this in the past, but didn't get it to work (didn't try that hard tho). Typically the pain point comes when you load a module that uses plugins, esp i18n, so be sure to try loading something from esri/dijit.

**Comment by jpeterson** [comment]
We'll set up [a separate JSAPI example](https://github.com/jpeterson/devsummit-2016-modern-tools/pull/1) - this is still useful on its own. It is the Esri Developer Summit, not the Esri JSAPI Summit, after all.

Perhaps we can work esri-leaflet in.

**Comment by tomwayson** [comment]
I don't really care if you show JSAPI or not. I'm just concerned that that example implies that you can load JSAPI classes w/ webpack, which I'm not sure is possible. If it's not, or you're not going to show it, I strongly recommend that you remove this line:

https://github.com/jpeterson/devsummit-2016-modern-tools/blob/master/example-webpack-amd/index.html#L20

Perhaps replace w/ Esri Leaflet script? ;)

**Comment by jpeterson** [comment]
Agreed. This entire example has become obsolete with the new JSAPI sample we'll be including.
